name: "tabdpt"
backend: "tensorrt_plan"
max_batch_size: 64

input [
  {
    name: "input_features"
    data_type: TYPE_BF16
    dims: [ 128 ]                # Trailing dimensions (batch dim is handled automatically)
  }
]
output [
  {
    name: "probabilities"
    data_type: TYPE_BF16
    dims: [ 10 ]
  }
]